config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'pages/info'
  get 'pages/home'

  resources :items


  root 'pages#home'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_ancestry

  def self.arrange_as_array(options={}, hash=nil)
    hash ||= arrange(options)

    arr = []
    hash.each do |node, children|
      arr << node
      arr += arrange_as_array(options, children) unless children.nil?
    end
    arr
  end

  def name_for_selects
    "#{'-' * depth} #{name}"
  end

  def possible_parents
    parents = Category.arrange_as_array(:order => 'name')
    return new_record? ? parents : parents - subtree
  end

  has_many :items



end

app/models/item.rb
class Item < ApplicationRecord

  mount_uploader :image, ImageUploader
  belongs_to :category

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new(:parent_id => params[:parent_id])

  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :desc, :parent_id)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # GET /items/1/edit
  def edit
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.category_id = params[:category_id]

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    @item.category_id = params[:category_id]
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
      @categories = Category.all.map{|c| [ c.name, c.id ] }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :image, :category_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end

  def home
    @items = Item.all
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="alert alert-warning" role="alert">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form.hidden_field :parent_id %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :desc %>
    <%= form.text_area :desc, id: :category_desc, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% if notice.present? %>
  <p class="alert alert-primary" role="alert">
    <%= notice %>
  </p>
<% end %>
<h1>Categories</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.desc %></td>
        <td><%= link_to "New Sub Category", new_category_path(:parent_id => category) %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= @category.name if @category.parent %>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @category.name %>
</h2>

<p>
  <%= @category.desc %>
</p>

<h3> Listings in this category </h3>
<div class="row">
  <% Item.where(category_id: @category.id).each do |item| %>
    <%= render 'items/item-card', item: item %>
  <% end %>
</div>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/items/_form.html.erb
<div class="row justify-content-center">
  <div class="col-md-6">

    <%= form_with(model: item, local: true) do |f| %>
      <% if item.errors.any? %>
        <div id="error_explanation" class="alert alert-warning" role="alert">
          <h4><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h4>

          <ul>
          <% item.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :category_id %>
        <%= select_tag(:category_id, options_for_select(@categories), :prompt => 'Select Category', class: 'form-control') %>
      </div>

      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, id: :item_title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :image %><br>
        <%= f.file_field :image, class: 'form-control' %>
        <% if f.object.image? %>
          <%= image_tag f.object.image.thumb.url %>
          <%= f.label :remove_image %>
          <%= f.check_box :remove_image %>
        <% end %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, id: :item_description, class: 'form-control' %>
      </div>



      <div class="form-group">
        <%= f.submit "List item", class: 'btn btn-primary' %>
      </div>
    <% end %>

  </div>
</div>

app/views/items/_item-card.html.erb
<div class="col-md-4 col-sm-6">
  <div class="card">
    <%= image_tag(item.image_url, class: 'card-img-top') if item.image.present? %>
    <div class="card-body">
      <h5 class="card-title"><%= link_to item.title, item %></h5>
      <p class="card-text"><%= truncate(item.description, length: 100) %></p>
      <%= link_to 'View', item, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<% if notice.present? %>
  <p class="alert alert-primary" role="alert">
    <%= notice %>
  </p>
<% end %>

<h1>Items</h1>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Description</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= image_tag(item.image_url :thumb) if item.image.present? %></td>
        <td><%= item.title %></td>
        <td><%= truncate(item.description, length: 100) %></td>
        <td><%= link_to Category.find(item.category_id).name, category_path(item.category_id) %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag(@item.image_url) if @item.image.present? %>

<h2>
  <%= @item.title %>
</h2>

<p>
  <%= simple_format(@item.description) %>
</p>



<%= link_to 'Edit', edit_item_path(@item), class: 'btn btn-primary btn-sm' %>
<%= link_to 'Back', items_path, class: 'btn btn-secondary btn-sm' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hireground.io</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "Hireground", root_url, :class => "navbar-brand" %>
        </div>

        <ul class="nav nav-pills">
          <li class="nav-item">
            <%= link_to "Manage Items", items_url, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
        </ul>
      </div>
    </nav>




    <div class="container">
      <%= yield %>
    </div>

    <footer>
      <hr>
      <div class="container">
        Hireground.io <%= Time.now.year %>
      </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>

app/views/pages/home.html.erb
<nav class="navbar navbar-light bg-light">
  <ul class="nav justify-content-center">
    <% @categories.each do |category| %>
      <li class="nav-item">
        <%= link_to category.name, category, class: 'nav-link' %>
      </li>
    <% end %>
  </ul>
</nav>



<div class="row">

  <% @items.each do |item| %>

    <div class="col-md-4 col-sm-6">
      <div class="card">
        <%= image_tag(item.image_url, class: 'card-img-top') if item.image.present? %>
        <div class="card-body">
          <h5 class="card-title"><%= link_to item.title, item %></h5>
          <p class="card-text"><%= truncate(item.description, length: 100) %></p>
          <%= link_to 'View', item, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>

  <% end %>

</div>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>